name: CI - Helpdesk API Tests

on:
  push:
    branches: [ main ]

env:
  CI: true
  NODE_OPTIONS: '--max-old-space-size=4096'
  CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          npm install
          npm ls

      - name: Run Cypress Smoke Tests
        uses: cypress-io/github-action@v6
        with:
          start: node server.js
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 10
          command: npm run test:smoke
          record: false

  regression-tests:
    needs: smoke-tests 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          npm install
          npm ls

      - name: Run Cypress Regression Tests
        uses: cypress-io/github-action@v6
        with:
          start: node server.js
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 10
          command: npm run test:regression
          record: false

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-test-reports
          path: cypress/reports/html